### ISSUE TITLE
docker-compose install method?

### ISSUE THREAD

**Issue by ericvlog** [arvida42/jackettio#1]
I have nginx proxy manager to make https working and successful install other addon on stremio.

becouse i have jackett & reversed proxy installed, seem use all in 1 installation no suite...

Thanks

**Comment by arvida42** [comment]
You just have to only run the addon container, example with compose:
```yml
version: "3.3"
name: jackettio
services:

  jackettio:
    image: arvida42/jackettio:latest
    container_name: jackettio
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATA_FOLDER=/data
      - JACKETT_URL=http://jacket_url
      - JACKETT_API_KEY=API_KEY
    restart: unless-stopped
    volumes:
      - jackettio-data:/data
    ports:
      - 4000:4000

volumes:
  jackettio-data:
```

**Comment by ericvlog** [comment]
sorry i got this error, git clone and inside have the files?
/.env.production: no such file or directory

**Comment by arvida42** [comment]
You don't have to clone the repo if you use docker.
Simply create a compose file with the informations in previous message. Remove the `env_file` key.

You docker-compose.yml should be:
```yml
version: "3.3"
name: jackettio
services:

  jackettio:
    image: arvida42/jackettio:latest
    container_name: jackettio
    environment:
      - NODE_ENV=production
      - DATA_FOLDER=/data
      - JACKETT_URL=http://jacket_url
      - JACKETT_API_KEY=API_KEY
    restart: unless-stopped
    volumes:
      - jackettio-data:/data
    ports:
      - 4000:4000

volumes:
  jackettio-data:
```

Configure your JACKETT_URL and JACKETT_API_KEY then run `docker compose up -d` commande.
