### ISSUE TITLE
[Bug] Self-hosted docker with premiumize; all returned links are broken

### ISSUE THREAD

**Issue by victorgveloso** [arvida42/jackettio#42]
**What am I experiencing?**
I am running Jackettio with premiumize. After selecting a movie, many streams are shown as expected (e.g., for Alien Romulus 8 out of the 20 releases found were cached, thus were listed in stremio). However, when click in any of those, I get a red unexpected error warning 30s video and the following stacktrace is logged:
```
GET /*******************/download/movie/tt18412256/a664d02009c072401ad09e29e7e8d9bac628e69b/Alien%20Romulus%201080p
jackett       | 11-29 20:17:29 Info Torznab search in RedeTorrent for Alien: Romulus => Found 20 releases [7981ms]
jackett       | 11-29 20:17:31 Info Torznab search in ApacheTorrent for Alien: Romulus => Found 20 releases [10525ms]
jackettio  | tt18412256 : PM : 36f53d289618bde502342a967e4399930669c57d : 5 files found
jackettio  | tt18412256 Error: No download for type movie and ID a664d02009c072401ad09e29e7e8d9bac628e69b
jackettio  |     at Module.getDownload (file:///home/node/app/src/lib/jackettio.js:430:11)
jackettio  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
jackettio  |     at async file:///home/node/app/src/index.js:177:17
jackettio  | tt18412256 : PM : 36f53d289618bde502342a967e4399930669c57d : get files ...
jackettio  | tt18412256 : PM : 36f53d289618bde502342a967e4399930669c57d : 5 files found
jackettio  | tt18412256 Error: No download for type movie and ID a664d02009c072401ad09e29e7e8d9bac628e69b
jackettio  |     at Module.getDownload (file:///home/node/app/src/lib/jackettio.js:430:11)
jackettio  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
jackettio  |     at async file:///home/node/app/src/index.js:177:17
```

<img width="1172" alt="image" src="https://github.com/user-attachments/assets/5cb3c42b-24c6-40a5-b5bb-9231c7b5f5db">

**How did I setup jackettio?**
I kept my docker-compose.yml from the time before real debrid had deprecated the cache-checking endpoint. All I did was `docker compose pull` and reconfigure my addon to use premiumize instead of real debrid.

```YAML
services:
  jackettio:
    image: arvida42/jackettio:latest
    container_name: jackettio
    environment:
      - NODE_ENV=production
      - DATA_FOLDER=/data
      - JACKETT_PASSWORD=password
      - JACKETT_URL=http
      - JACKETT_API_KEY=key
      - TMDB_ACCESS_TOKEN=token
    ports:
      - 4000:4000
    volumes:
      - ./data:/data
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.jackettio.entrypoints=web,websecure"
      - "traefik.http.routers.jackettio.rule=Host(url)"
      - "traefik.http.services.jackettio.loadbalancer.server.port=port"
      - "traefik.http.routers.jackettio.tls=true"
      - "traefik.http.routers.jackettio.tls.certresolver=production"
    restart: unless-stopped

networks:
  traefik_default:
    external: true
```

Any idea of why it's happening?
